/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aviso.view;

import aviso.model.Conexao;
import aviso.model.Extenso;
import aviso.model.Gerar_Relatorio;
import aviso.model.Servidor;
import aviso.utilitarios.Mensagens;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.Normalizer;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import net.sf.jasperreports.engine.JRException;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.output.XMLOutputter;
import org.joda.time.DateTime;

/**
 *
 * @author wanderlei
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        data_aquisicao_inicial = new javax.swing.JFormattedTextField();
        data_aquisicao_final = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        data_gozo_inicial = new javax.swing.JFormattedTextField();
        data_gozo_final = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRetorno = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txt_mes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_data_emissao = new com.toedter.calendar.JDateChooser();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        bt_imprimirtodos = new javax.swing.JButton();
        txt_ano = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txt_matricula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_nome_funcionario = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txt_Faltas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        try {
            data_aquisicao_inicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            data_aquisicao_final.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        data_aquisicao_final.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                data_aquisicao_finalFocusLost(evt);
            }
        });
        data_aquisicao_final.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                data_aquisicao_finalKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("a");

        jLabel8.setText("Período de Gozo");

        try {
            data_gozo_inicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            data_gozo_final.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        data_gozo_final.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                data_gozo_finalFocusLost(evt);
            }
        });
        data_gozo_final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_gozo_finalActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("a");

        jLabel10.setText("Data de Retorno");

        try {
            txtRetorno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setText("Data de Emissão");

        txt_mes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel1.setText("Mês");

        jLabel2.setText("Ano");

        bt_imprimirtodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aviso/printer.png"))); // NOI18N
        bt_imprimirtodos.setText("Imprimir");
        bt_imprimirtodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_imprimirtodosActionPerformed(evt);
            }
        });

        txt_ano.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aviso/delete.png"))); // NOI18N
        jButton2.setText("Fechar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Aviso de Férias");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aviso/process_info.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Matricula");

        txt_matricula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_matricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_matriculaKeyReleased(evt);
            }
        });

        jLabel5.setText("Funcionário");

        txt_nome_funcionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_nome_funcionario.setToolTipText("");
        txt_nome_funcionario.setEnabled(false);

        jLabel6.setText("Período de Aquisçâo");

        txt_Faltas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel11.setText("Faltas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_imprimirtodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(113, 113, 113)
                                        .addComponent(jButton3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(data_aquisicao_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(data_aquisicao_final))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel6)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(data_gozo_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(data_gozo_final, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel10)
                                            .addComponent(txt_data_emissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txt_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel2)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(jLabel11))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(64, 64, 64)
                                                .addComponent(txt_Faltas, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_matricula, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txt_nome_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Faltas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nome_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(data_aquisicao_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(data_aquisicao_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_data_emissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(data_gozo_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data_gozo_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(bt_imprimirtodos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(363, 378));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 private static String format(String pattern, Object value) {
        try {
            MaskFormatter mask = new MaskFormatter(pattern);
            mask.setValueContainsLiteralCharacters(false);
            return mask.valueToString(value);
        } catch (ParseException e) {
            throw new RuntimeException(e);
        }
    }

    public static String limpaCaracteres(String palavra) {
        String aux = "";
        aux = Normalizer.normalize(palavra, java.text.Normalizer.Form.NFD);
        aux = aux.replaceAll("[^\\p{ASCII}]", "");
        return aux;
    }

    public void gerar_arquivo_manual() {
        String total_falta = "";
        String matricula = "";
        String nome = "";
        String cnpf = "";
        String nome_cargo = "";
        String nome_empresa = "";
        String cnpj_empresa = "";
        String cidade = "";
        String uf = "";
        String valor_normal_extenso = "";
        String valor_recibo_extenso = "";
        String aquisicao_inicial = "";
        String aquisicao_final = "";
        String gozo_inicial = "";
        String gozo_final = "";
        String retorno = "";
        String valor_recibo = "";
        Date d_emissao = new Date();
        DateFormat formato_normal = new SimpleDateFormat("dd/MM/YYYY");
        DateFormat formato_full = DateFormat.getDateInstance(1);
        d_emissao = txt_data_emissao.getDate();
        String emissao = formato_full.format(d_emissao);
        emissao = limpaCaracteres(emissao.toUpperCase());
        aquisicao_inicial = data_aquisicao_inicial.getText();
        aquisicao_final = data_aquisicao_final.getText();
        gozo_inicial = data_gozo_inicial.getText();
        gozo_final = data_gozo_final.getText();
        retorno = txtRetorno.getText();
        try {
            Conexao.abrirConexao();
            Statement stmt = Conexao.con.createStatement();
            String sql_pesquisar = (new StringBuilder()).append("select\nf.codigo as matricula,\nf.nome,\nf.cnpf,\nc.nome as nome_cargo\nfrom funcionario f\njoin cargo c on c.codigo = f.codigo_cargo\nwhere f.codigo = ").append(txt_matricula.getText()).append("").toString();
            for (ResultSet rs = stmt.executeQuery(sql_pesquisar); rs.next();) {
                nome = rs.getString("nome");
                matricula = rs.getString("matricula");
                cnpf = rs.getString("cnpf");
                nome_cargo = rs.getString("nome_cargo");
            }
            cnpf = format("###.###.###-##", cnpf);
            String sql_pesquisar_empresa = " select e.nome, e.cnpj, e.cidade, e.uf from empresa  e";
            for (ResultSet rs_empresa = stmt.executeQuery(sql_pesquisar_empresa); rs_empresa.next();) {
                nome_empresa = rs_empresa.getString("nome");
                cnpj_empresa = rs_empresa.getString("cnpj");
                cidade = rs_empresa.getString("cidade");
                uf = rs_empresa.getString("uf");
            }

            cnpj_empresa = format("##.###.###/####-##", cnpj_empresa);
            String sql_pesquisar_valor_recibo = (new StringBuilder()).append("select\nv.valor\nfrom variavel v\njoin provento p on p.codigo = v.provento\nwhere ((v.provento = 18 or v.provento = 47) and v.ano = ").append(txt_ano.getText()).append(" and v.mes = ").append(txt_mes.getText()).append(" and v.matricula = ").append(txt_matricula.getText()).append(")").toString();
            for (ResultSet rs_recibo = stmt.executeQuery(sql_pesquisar_valor_recibo);
                    rs_recibo.next();) {
                valor_recibo = rs_recibo.getString("valor");
            }
            if (!(valor_recibo.isEmpty())) {

                Extenso entenso_valor_recibo = new Extenso(Double.parseDouble(valor_recibo));
                valor_recibo_extenso = entenso_valor_recibo.toString();
                Element aviso = new Element("Aviso_Ferias");
                Document documento = new Document(aviso);
                Element servidor = new Element("Servidor");
                Element nome_servidor = new Element("nome_servidor");
                nome_servidor.setText(nome);
                Element matricula_servidor = new Element("matricula");
                matricula_servidor.setText(matricula);
                Element total_faltas = new Element("total_faltas");
                if (txt_Faltas.getText().equals("")) {
                    total_faltas.setText("0.00");
                } else {
                    total_faltas.setText(txt_Faltas.getText());
                }
                Element cpf_servidor = new Element("cnpf");
                cpf_servidor.setText(cnpf);
                Element cargo = new Element("nome_cargo");
                cargo.setText(nome_cargo);
                Element data_emissao_xml = new Element("data_emissao");
                data_emissao_xml.setText(emissao);
                Element data_aquisicao_inicial_xml = new Element("aquisicao_inicial");
                data_aquisicao_inicial_xml.setText(aquisicao_inicial);
                Element data_aquisicao_final_xml = new Element("aquisicao_final");
                data_aquisicao_final_xml.setText(aquisicao_final);
                Element data_gozo_inicial_xml = new Element("gozo_inicial");
                data_gozo_inicial_xml.setText(gozo_inicial);
                Element data_gozo_final_xml = new Element("gozo_final");
                data_gozo_final_xml.setText(gozo_final);
                Element data_retorno_xml = new Element("data_retorno");
                data_retorno_xml.setText(retorno);
                Element valor_recibo_extenso_xml = new Element("valor_recibo_extenso");
                valor_recibo_extenso_xml.setText(valor_recibo_extenso.toUpperCase());
                Element valor_recibo_xml = new Element("valor_recibo");
                valor_recibo_xml.setText(valor_recibo);
                Element nome_empresa_xml = new Element("nome_empresa");
                nome_empresa_xml.setText("PREFEITURA MUNICIPAL DE AUGUSTINOPOLIS");
                Element cnpj_empresa_xml = new Element("cnpj_empresa");
                cnpj_empresa_xml.setText(cnpj_empresa);
                Element cidade_xml = new Element("cidade");
                cidade_xml.setText("AUGUSTINOPOLIS");
                Element uf_xml = new Element("uf");
                uf_xml.setText(uf);
                String sql_tabela = (new StringBuilder()).append("select\nv.matricula,\nv.valor,\nIIF(v.referencia is null, '-',v.referencia) as referencia,\np.codigo as cod_provento,\np.nome as nome_provento\n\nfrom variavel v\njoin provento p on p.codigo = v.provento\nwhere v.ano = ").append(txt_ano.getText()).append(" and v.mes = ").append(txt_mes.getText()).append(" and v.matricula = ").append(matricula).append(" and v.sequencia <> 13 order by p.codigo").toString();
                ResultSet rs_tabela = stmt.executeQuery(sql_tabela);
                Element proventos = new Element("Proventos");
                int cod_prov = 0;
                double des = 0.0D;
                double pro = 0.0D;
                double liq = 0.0D;
                Element provento;
                for (; rs_tabela.next(); proventos.addContent(provento)) {
                    provento = new Element("provento");
                    cod_prov = Integer.parseInt(rs_tabela.getString("cod_provento"));
                    provento.setAttribute("codigo", String.valueOf(cod_prov));
                    provento.setAttribute("nome", rs_tabela.getString("nome_provento"));
                    provento.setAttribute("ref", rs_tabela.getString("referencia"));
                    if (cod_prov > 500) {
                        des += Double.parseDouble(rs_tabela.getString("valor"));
                        provento.setAttribute("descontos", rs_tabela.getString("valor"));
                    } else {
                        pro += Double.parseDouble(rs_tabela.getString("valor"));
                        provento.setAttribute("redimento", rs_tabela.getString("valor"));
                    }
                }

                liq = pro - des;
                Element total_descontos_xml = new Element("total_descontos");
                total_descontos_xml.setText(String.valueOf(des));
                Element total_provento_xml = new Element("total_porvento");
                total_provento_xml.setText(String.valueOf(pro));
                Element total_liquido_xml = new Element("total_liquido");
                total_liquido_xml.setText(String.valueOf(liq));
                stmt.close();
                Conexao.fecharConexao();
                servidor.addContent(nome_servidor);
                servidor.addContent(matricula_servidor);
                servidor.addContent(cpf_servidor);
                servidor.addContent(cargo);
                servidor.addContent(data_emissao_xml);
                servidor.addContent(data_aquisicao_inicial_xml);
                servidor.addContent(data_aquisicao_final_xml);
                servidor.addContent(data_gozo_inicial_xml);
                servidor.addContent(data_gozo_final_xml);
                servidor.addContent(data_retorno_xml);
                servidor.addContent(valor_recibo_extenso_xml);
                servidor.addContent(valor_recibo_xml);
                servidor.addContent(nome_empresa_xml);
                servidor.addContent(cnpj_empresa_xml);
                servidor.addContent(cidade_xml);
                servidor.addContent(uf_xml);
                servidor.addContent(total_provento_xml);
                servidor.addContent(total_descontos_xml);
                servidor.addContent(total_liquido_xml);
                servidor.addContent(total_faltas);
                servidor.addContent(proventos);
                aviso.addContent(servidor);
                XMLOutputter xout = new XMLOutputter();
                FileWriter arquivo = new FileWriter(new File((new StringBuilder()).append(System.getProperty("user.dir") + "\\aviso-").append(matricula).append(".xml").toString()));
                xout.output(documento, arquivo);
            } else {
                JOptionPane.showMessageDialog(null, "Erro!\nConfigure as remunerações de férias!");
                return;
            }

        } catch (SQLException ex) {
            //  Logger.getLogger(avisoferias / tela.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            //  Logger.getLogger(avisoferias / tela.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Gerar_Relatorio.gerar_aviso(txt_matricula.getText());
        } catch (FileNotFoundException ex) {
            //Logger.getLogger(aviso / tela.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(rootPane, ex);
        } catch (JRException ex) {
            //  Logger.getLogger(avisoferias / tela.getName()).log(Level.SEVERE, null, ex);
        }

    }


    private void data_gozo_finalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_data_gozo_finalFocusLost
        // TODO add your handling code here:
        txtRetorno.setText(data_gozo_final.getText());
    }//GEN-LAST:event_data_gozo_finalFocusLost

    private void bt_imprimirtodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_imprimirtodosActionPerformed
        // TODO add your handling code here:
        gerar_arquivo_manual();
    }//GEN-LAST:event_bt_imprimirtodosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TelaConexao conectar = new TelaConexao();
        conectar.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_matriculaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_matriculaKeyReleased
        // TODO add your handling code here:
        try {
            Conexao.abrirConexao();
            Statement stmt = Conexao.con.createStatement();
            String sql_pesquisar = (new StringBuilder()).append("select F.nome from FUNCIONARIO F where F.CODIGO = ").append(txt_matricula.getText()).append("").toString();
            for (ResultSet rs = stmt.executeQuery(sql_pesquisar); rs.next();
                    txt_nome_funcionario.setText(rs.getString("nome")));

        } catch (Exception exception) {

        }
    }//GEN-LAST:event_txt_matriculaKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // TODO add your handling code here:
        Date data_emissao = new Date();
        txt_data_emissao.setDate(data_emissao);
        DateTime dateTime = new DateTime();
        txt_ano.setText(dateTime.toString("yyyy"));
        txt_mes.setText(dateTime.toString("MM"));
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //dispose();
        Mensagens.mensagem_sair_sistema();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void data_aquisicao_finalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_data_aquisicao_finalKeyReleased
        // TODO add your handling code here:


    }//GEN-LAST:event_data_aquisicao_finalKeyReleased

    private void data_aquisicao_finalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_data_aquisicao_finalFocusLost
        // TODO add your handling code here:
        
     String faltas = Servidor.faltas(txt_Faltas.getText(), data_aquisicao_inicial.getText(), data_aquisicao_final.getText(),txt_matricula.getText());
      txt_Faltas.setText(faltas);
      /*  
        if (txt_Faltas.getText().trim().equals("")) {
            String total_falta = "";
            String mes_inicio = "";
            String data_ano_inicio = "";
            String mes_fim = "";
            String data_ano_fim = "";
            String matricula = "";
            String messagem = "";

            mes_inicio = data_aquisicao_inicial.getText().substring(3, 5);
            data_ano_inicio = data_aquisicao_inicial.getText().substring(6, 10);
            if (mes_inicio.trim().equals("")) {
                messagem = "Data inicio de aquisição inválida!";
            }
            data_ano_fim = data_aquisicao_final.getText().substring(6, 10);
            mes_fim = data_aquisicao_final.getText().substring(3, 5);

            if (mes_fim.trim().equals("")) {
                messagem = messagem + "\nData fim de aquisição inválida!";
            }

            if (!(messagem.trim().equals(""))) {
                Mensagens.mensagem_tela("Erro data", messagem, "erro");
                return;
            }

            matricula = txt_matricula.getText();

            System.out.println("mes ini: " + mes_inicio);
            System.out.println("ano ini: " + data_ano_inicio);
            System.out.println("mes fim: " + mes_fim);
            System.out.println("ano fim: " + data_ano_fim);

            Conexao.abrirConexao();
            Statement stmt;
            try {
                stmt = Conexao.con.createStatement();
                String sql_pesquisar_falta = (new StringBuilder())
                        .append("select SUM(V.referencia)as falta FROM variavel V WHERE V.provento = 501 AND ((ANO >= ")
                        .append(data_ano_inicio)
                        .append(" AND MES >=")
                        .append(mes_inicio)
                        .append(") AND (ANO <= ")
                        .append(data_ano_fim)
                        .append(" AND MES <=")
                        .append(mes_fim)
                        .append(")) AND  v.matricula =")
                        .append(matricula).toString();
                System.out.println(sql_pesquisar_falta);

                for (ResultSet rs_falta = stmt.executeQuery(sql_pesquisar_falta);
                        rs_falta.next();) {
                    total_falta = rs_falta.getString("falta");

                }
                txt_Faltas.setText(total_falta);
                            } catch (SQLException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        }*/

    }//GEN-LAST:event_data_aquisicao_finalFocusLost

    private void data_gozo_finalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_gozo_finalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_gozo_finalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_imprimirtodos;
    private javax.swing.JFormattedTextField data_aquisicao_final;
    private javax.swing.JFormattedTextField data_aquisicao_inicial;
    private javax.swing.JFormattedTextField data_gozo_final;
    private javax.swing.JFormattedTextField data_gozo_inicial;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JFormattedTextField txtRetorno;
    private javax.swing.JTextField txt_Faltas;
    private javax.swing.JTextField txt_ano;
    private com.toedter.calendar.JDateChooser txt_data_emissao;
    private javax.swing.JTextField txt_matricula;
    private javax.swing.JTextField txt_mes;
    private javax.swing.JTextField txt_nome_funcionario;
    // End of variables declaration//GEN-END:variables
}
